spring:
  application:
    name: microservice-consumer-movie-ribbon
#security:
#  basic:
#    enabled: true
#  user:
#    name: user
#    password: password123
server:
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true