spring:
  application:
    name: microservice-gateway-zuul
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
